import {createApp} from 'vue'
import App from './App.vue'

import {IonicVue} from '@ionic/vue';

import '@/assets/utilities.scss';
import '@/assets/fonts.scss';
import '@/assets/reset.scss';

/* Core CSS required for Ionic components to work properly */
import '@ionic/vue/css/core.css';

/* Basic CSS for apps built with Ionic */
import '@ionic/vue/css/normalize.css';
import '@ionic/vue/css/structure.css';
import '@ionic/vue/css/typography.css';

/* Theme variables */
import './theme/variables.css';

/* Vuex store */
import vuex from '@/vuex';

/* Autogenerated routes */
import router from '@/router';

/* Ionic Custom Plugins and Components (Formerly Nuxt's) */
import plugins from "@/plugins";

const app = createApp(App)
  .use(IonicVue)
  .use(router)
  .use(vuex)
  .use(plugins);

router.isReady().then(() => {
  app.mount('#app');
});
