name: Build & Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Vue Build
        run: |
          npm ci
          npm run build
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: master
          repo: bonfire-xmpp/bonfire-xmpp.github.io
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT: ${{ secrets.BUILD_REPO_PAT }}
